spring:
  application:
    name: roc
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/josetan?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    host: #IP
    port: 5672
    username: guest #默认
    password: guest
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis:
  type-aliases-package: com.example.roc.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true